### ISSUE TITLE
Hi Kaan 

### ISSUE THREAD

**Issue by Bas-oneseconds** [kaanguru/mutate-question#1]
Hi Kaan thanks to this repo I got Apollo to work in my project. I was wondering if you know if subscriptions are possible with Nativescript (I'm on 8) Vue & Apollo. Together with another WebSocket like @klippa/websocket for example. I hope this message wil reach you, have a great day!

**Comment by kaanguru** [comment]
Unfortunately, I have never tried subscriptions but it should work as expected.

Check out the vue implementation example in https://github.com/Akryum/apollo-server-example

https://vue-apollo.netlify.app/guide/apollo/subscriptions.html
